CODE RUB: Code Cleanup ReactionsApiTests.cs #334
cjdutoit/Glory2Him.Api pull request #335
Opened 2022-01-23 07:29 UTC by imjane5

Simplify namespace reference: >> Added the respective library 

Explicit left-hand side: The datatype has been specified 

this qualifier: qualifier added

Implicit left-hand side: "var" datatype has been used

Remove extra line: extra line removed.

2022-01-23 07:30 UTC, ShriHumrudha requested changes

2022-01-23 07:30 UTC, ShriHumrudha commented on G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs
>              List<Web.Models.Reactions.Reaction> reactions = GetStorageReactions(userId);
You can simplify this namespace as well.

2022-01-23 07:30 UTC, ShriHumrudha commented on G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs
>                  new List<Web.Models.Reactions.Reaction>();
You can move this line to above.

2022-01-23 07:33 UTC, imjane5 commented
Closes #334

2022-01-24 22:01 UTC, ShriHumrudha requested changes

2022-01-24 22:01 UTC, ShriHumrudha commented on G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs
> +            var reactions = GetStorageReactions(userId);
This has to be explicit

2022-01-24 22:01 UTC, ShriHumrudha commented on G2H.Api.Web.Tests.Acceptance/Apis/Reactions/ReactionsApiTests.cs
>          private static List<Web.Models.Reactions.Reaction> GetStorageReactions(Guid userId)
Fis this namespace as well. Verify any other occurrences too.

2022-02-01 02:09 UTC, ShriHumrudha approved these changes

2022-02-03 08:51 UTC, cjdutoit commented
Thanks @imjane5

2022-02-03 08:52 UTC, cjdutoit approved these changes

2022-02-03 08:52 UTC, merged